

package Enum;


public enum Mazo {
    ESPADA_UNO, ESPADA_DOS, ESPADA_TRES, ESPADA_CUATRO, ESPADA_CINCO, ESPADA_SEIS, ESPADA_SIETE, ESPADA_DIEZ, ESPADA_ONCE, ESPADA_DOCE,COPA_UNO, COPA_DOS, COPA_TRES, COPA_CUATRO, COPA_CINCO, COPA_SEIS, COPA_SIETE, COPA_DIEZ, COPA_ONCE, COPA_DOCE, BASTO_UNO, BASTO_DOS, BASTO_TRES, BASTO_CUATRO, BASTO_CINCO, BASTO_SEIS, BASTO_SIETE,BASTO_DIEZ,BASTO_ONCE, BASTO_DOCE,ORO_UNO, ORO_DOS, ORO_TRES, ORO_CUATRO, ORO_CINCO, ORO_SEIS, ORO_SIETE, ORO_DIEZ, ORO_ONCE, ORO_DOCE;
}

